server:
  port: 8080

data:
  mysql:
    user: root:123456@tcp(localhost:3306)/go_gin_web?charset=utf8mb4&parseTime=True&loc=Local

qdrant:
  url: localhost:6334

log:
  log_level: debug
  encoding: console           # json or console
  log_file_name: "./logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true

security:
  jwt:
    key: wry
    expires: 3600

embedding:
#  zhipu:
#    apiKey: c95ef5a388b0a3809b0e6b94767d6336.cMqckHSbhYHCkyUF
#    embeddingUrl: https://open.bigmodel.cn/api/paas/v3/model-api/text_embedding/invoke
  xunfei:
    appid: 8eec9a9a
    apiKey: 63b8322d0f0458e2bc509a0d68b9d85b
    apiSecret: NmFiMThkMWVhM2EwOGI4ZDk2NDkxMTFj
    embeddingUrl: https://knowledge-retrieval.cn-huabei-1.xf-yun.com/v1/aiui/embedding/query
