// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"go-gin-demo/internal/routers"
	"go-gin-demo/internal/server"
	"go-gin-demo/internal/system/handler"
	"net/http"
)

// Injectors from wire.go:

func NewServer(viperViper *viper.Viper) http.Handler {
	engine := server.NewServer()
	userHandler := handler.NewUserHandler()
	systemHandler := handler.NewSystemHandler(userHandler)
	httpHandler := routers.NewRouter(engine, systemHandler)
	return httpHandler
}

// wire.go:

var ServerSet = wire.NewSet(server.NewServer)

var RouterSet = wire.NewSet(routers.NewRouter)

var HandlerSet = wire.NewSet(handler.NewUserHandler, handler.NewSystemHandler)
