version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=root
    volumes:
      - ./data/mysql:/var/lib/mysql
#      - ./conf/mysql/conf.d:/etc/mysql/conf.d
      - ./scripts:/docker-entrypoint-initdb.d
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"