version: '3'

services:
  web:
    image: go-gin-web:latest
    ports:
      - "8080:8080"
    volumes:
      - ./conf/web/config:/data/app/conf
      - ./data/web/logs:/data/app/logs
  mysql:
    image: mysql:latest
    ports:
      - "3380:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=root
    volumes:
      - ./data/mysql/user:/var/lib/mysql
      - ./conf/mysql/conf.d:/etc/mysql/conf.d
      - ./scripts:/docker-entrypoint-initdb.d