version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=root
    volumes:
      - ./data/mysql:/var/lib/mysql
#      - ./conf/mysql/conf.d:/etc/mysql/conf.d
      - ./scripts:/docker-entrypoint-initdb.d
  web:
    image: go-gin-web:latest
    ports:
      - "8080:8080"
    volumes:
      - ./conf/web/config:/data/app/config
      - ./data/web/logs:/data/app/logs
    depends_on:
      - mysql